FROM openjdk:8-jdk-slim as builder

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src
RUN ["chmod","+x","./gradlew"]
RUN ["./gradlew", "bootJar"]


COPY --from=builder build/libs/*.jar app.jar
ENTRYPOINT [ "java" ]
RUN ["-jar","-Dspring.profiles.active=gcp", "/app.jar"]
EXPOSE 8081
